### ISSUE TITLE
fails to parse package.json for yarn

### ISSUE THREAD

**Issue by simevo** [LeoIannacone/npm2deb#87]
```
npm2deb yarn
```
does not fill the Depends and Build-Depends.

This in turn prevents the `js_task_edit.py` script (https://anonscm.debian.org/cgit/pkg-javascript/js-task-wiki-edit.git) from generating a proper Task

**Comment by shanavas786** [comment]
@simevo, nm2deb works as expected.

- yarn's `package.json` from npm does not list any dependencies or dev deps. you can check with `npm v yarn`. That is why dependencies are not filled in `d/control` file
- behavior of `js_task_edit.py` doesn't depend on `npm2deb`. The observed behavior results from reason mentioned above. However you can use `js_task_edit.py -f <package.json from github repo>` to generate tasks
- `dh_install` failure (`dh_install: Cannot find (any matches for) "lib"`) is due to the difference in directory structure between tarballs of npm registry and github

**Comment by simevo** [comment]
many thanks for the clarifications

your tip to use `js_task_edit.py -f yarn/package.json` made it, but I had to manually remove the line with `eslint-plugin-yarn-internal` else the script chokes on that
